<a href="https://colab.research.google.com/github/lilreel/GDSC_USU/blob/main/2.%20Machine%20Learning/GDSC_TF_dengan_dataset_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
datatrain = pd.read_csv('iris_train.csv')
datatest = pd.read_csv('iris_test.csv')

In [ ]:
datatrain.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           5.1          3.4           1.5          0.2      Iris-setosa
1           6.3          2.5           5.0          1.9   Iris-virginica
2           5.9          3.0           4.2          1.5  Iris-versicolor
3           5.7          2.6           3.5          1.0  Iris-versicolor
4           7.7          2.8           6.7          2.0   Iris-virginica

In [ ]:
datatest.head()

sepal_length  sepal_width  petal_length  petal_width          species
0           5.7          4.4           1.5          0.4      Iris-setosa
1           5.0          3.4           1.6          0.4      Iris-setosa
2           6.1          2.8           4.7          1.2  Iris-versicolor
3           6.3          3.3           4.7          1.6  Iris-versicolor
4           5.0          3.6           1.4          0.2      Iris-setosa

In [ ]:
datatrain['species'].value_counts()

Iris-versicolor    41
Iris-virginica     34
Iris-setosa        30
Name: species, dtype: int64

In [ ]:
datatrain.loc[datatrain['species']=='Iris-setosa', 'species'] = 0
datatrain.loc[datatrain['species']=='Iris-versicolor', 'species'] = 1
datatrain.loc[datatrain['species']=='Iris-virginica', 'species'] = 2

In [ ]:
datatrain

sepal_length  sepal_width  petal_length  petal_width species
0             5.1          3.4           1.5          0.2       0
1             6.3          2.5           5.0          1.9       2
2             5.9          3.0           4.2          1.5       1
3             5.7          2.6           3.5          1.0       1
4             7.7          2.8           6.7          2.0       2
..            ...          ...           ...          ...     ...
100           5.4          3.4           1.7          0.2       0
101           5.6          2.5           3.9          1.1       1
102           6.4          2.9           4.3          1.3       1
103           7.9          3.8           6.4          2.0       2
104           5.4          3.0           4.5          1.5       1

[105 rows x 5 columns]

In [ ]:
datatrain = datatrain.apply(pd.to_numeric)

In [ ]:
datatrain_array

array([[5.1, 3.4, 1.5, 0.2, 0. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [5.7, 2.6, 3.5, 1. , 1. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [6. , 3. , 4.8, 1.8, 2. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.4, 2.8, 5.6, 2.2, 2. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [6.9, 3.1, 5.4, 2.1, 2. ],
       [5.9, 3. , 5.1, 1.8, 2. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.8, 2

In [ ]:
xtrain = datatrain_array[:,:4]

In [ ]:
xtrain

array([[5.1, 3.4, 1.5, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [5.9, 3. , 4.2, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [7.7, 2.8, 6.7, 2. ],
       [6. , 3. , 4.8, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [5.8, 2.7, 4.1, 1. ],
       [5.5, 2.3, 4. , 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.1, 2.8, 4. , 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [6.8, 3. , 5.5, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.5, 2.4, 3.8, 1.1],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.8, 5.1, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [6.4, 2.8, 5.6, 2.2],
       [6.7, 3. , 5.2, 2.3],
       [4.6, 3.1, 1.5, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.9, 3. , 5.1, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [5.1, 3.5, 1.4, 0.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.2, 2.2, 4.5, 1.5],
       [4.9, 3

In [ ]:
ytrain = datatrain_array[:,4]

In [ ]:
ytrain

array([0., 2., 1., 1., 2., 2., 2., 1., 1., 1., 0., 0., 2., 1., 1., 2., 0.,
       2., 1., 1., 2., 2., 2., 2., 0., 2., 2., 2., 0., 1., 1., 1., 1., 1.,
       0., 0., 2., 1., 1., 2., 1., 2., 0., 2., 0., 2., 1., 1., 1., 0., 2.,
       1., 2., 0., 0., 1., 0., 0., 2., 1., 0., 0., 2., 2., 0., 0., 0., 0.,
       2., 0., 0., 2., 2., 2., 1., 1., 2., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 2., 0., 1., 0., 1.,
       1., 2., 1.])

In [ ]:
#tf meminta label dalam bentuk one hot encoding
from tensorflow.keras.utils import to_categorical
cat_ytrain = to_categorical(ytrain)

In [ ]:
cat_ytrain

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Model

tf.random.set_seed(1103)

In [ ]:
class Net(Model):
  def __init__(self):
    super(Net, self).__init__()
    self.d1 = Dense(3, activation = 'relu')
    self.d2 = Dense(3, activation = 'softmax')

  def call(self, x):
     x = self.d1(x)
     return self.d2(x)

modelkita = Net()

In [ ]:
#menggunakan algoritma SGD (Stochastic Gradient Descent)
optimizers = tf.keras.optimizers.SGD(learning_rate = 0.01)

In [ ]:
#gunain algoritma untuk menghitung error rate - crossentropy
criterion = tf.keras.losses.CategoricalCrossentropy()

Alur Training
1. Input data ke model untuk mendapatkan output model
2. hitung eror antara output dengan label
3. hitung gradient error
4. update bobot menggunakan algoritma optimasi (SGD)

50 epoch

In [ ]:
for epoch in range(50):
  with tf.GradientTape() as tape:
    out = modelkita(xtrain)
    loss = criterion(cat_ytrain, out)

    print("%d / 50 -- loss = %.4f " % (epoch, loss.numpy()))

  gradient = tape.gradient(loss, modelkita.trainable_variables)
  optimizers.apply_gradients(zip(gradient, modelkita.trainable_variables))

0 / 50 -- loss = 2.3130 
1 / 50 -- loss = 1.9709 
2 / 50 -- loss = 1.6995 
3 / 50 -- loss = 1.5098 
4 / 50 -- loss = 1.3983 
5 / 50 -- loss = 1.3164 
6 / 50 -- loss = 1.2531 
7 / 50 -- loss = 1.2053 
8 / 50 -- loss = 1.1703 
9 / 50 -- loss = 1.1455 
10 / 50 -- loss = 1.1283 
11 / 50 -- loss = 1.1164 
12 / 50 -- loss = 1.1082 
13 / 50 -- loss = 1.1025 
14 / 50 -- loss = 1.0983 
15 / 50 -- loss = 1.0952 
16 / 50 -- loss = 1.0927 
17 / 50 -- loss = 1.0905 
18 / 50 -- loss = 1.0887 
19 / 50 -- loss = 1.0869 
20 / 50 -- loss = 1.0853 
21 / 50 -- loss = 1.0837 
22 / 50 -- loss = 1.0822 
23 / 50 -- loss = 1.0807 
24 / 50 -- loss = 1.0792 
25 / 50 -- loss = 1.0777 
26 / 50 -- loss = 1.0762 
27 / 50 -- loss = 1.0747 
28 / 50 -- loss = 1.0732 
29 / 50 -- loss = 1.0717 
30 / 50 -- loss = 1.0703 
31 / 50 -- loss = 1.0688 
32 / 50 -- loss = 1.0673 
33 / 50 -- loss = 1.0658 
34 / 50 -- loss = 1.0643 
35 / 50 -- loss = 1.0628 
36 / 50 -- loss = 1.0614 
37 / 50 -- loss = 1.0599 
38 / 50 -- loss = 1.05

In [ ]:
#ambil nilai terbesar setiap kelasnya sebagai prediksi
prediction = tf.argmax(out, axis = 1)


#hitung hasil match dari hasil prediksi dengan label actual
total_benar = tf.reduce_sum(tf.cast(tf.equal(prediction, ytrain), tf.int32))

accuration = total_benar/len(cat_ytrain) *100

In [ ]:
print(accuration)

tf.Tensor(67.61904761904762, shape=(), dtype=float64)


*Testing Model Accuration*

In [ ]:
datatest.loc[datatest['species']=='Iris-setosa', 'species'] = 0
datatest.loc[datatest['species']=='Iris-versicolor', 'species'] = 1
datatest.loc[datatest['species']=='Iris-virginica', 'species'] = 2

In [ ]:
datatest

sepal_length  sepal_width  petal_length  petal_width species
0            5.7          4.4           1.5          0.4       0
1            5.0          3.4           1.6          0.4       0
2            6.1          2.8           4.7          1.2       1
3            6.3          3.3           4.7          1.6       1
4            5.0          3.6           1.4          0.2       0
5            4.4          3.0           1.3          0.2       0
6            4.7          3.2           1.6          0.2       0
7            5.1          2.5           3.0          1.1       1
8            6.5          3.0           5.5          1.8       2
9            7.4          2.8           6.1          1.9       2
10           5.5          2.6           4.4          1.2       1
11           6.2          3.4           5.4          2.3       2
12           5.0          3.5           1.3          0.3       0
13           7.7          3.0           6.1          2.3       2
14           4.6          3.2           1.4          0.2       0
15           4.8          3.4           1.9          0.2       0
16           5.7          2.8           4.5          1.3       1
17           6.7          3.3           5.7          2.1       2
18           5.4          3.4           1.5          0.4       0
19           4.4          2.9           1.4          0.2       0
20           4.5          2.3           1.3          0.3       0
21           6.0          2.2           5.0          1.5       2
22           6.9          3.1           5.1          2.3       2
23           6.3          2.7           4.9          1.8       2
24           6.7          3.1           4.4          1.4       1
25           5.6          2.8           4.9          2.0       2
26           5.1          3.8           1.5          0.3       0
27           4.8          3.0           1.4          0.3       0
28           7.1          3.0           5.9          2.1       2
29           6.1          3.0           4.9          1.8       2
30           5.5          3.5           1.3          0.2       0
31           4.7          3.2           1.3          0.2       0
32           4.4          3.2           1.3          0.2       0
33           4.8          3.0           1.4          0.1       0
34           6.4          3.1           5.5          1.8       2
35           4.3          3.0           1.1          0.1       0
36           5.8          2.7           5.1          1.9       2
37           5.6          2.9           3.6          1.3       1
38           7.2          3.6           6.1          2.5       2
39           5.7          2.5           5.0          2.0       2
40           6.9          3.1           4.9          1.5       1
41           6.5          3.2           5.1          2.0       2
42           6.0          2.2           4.0          1.0       1
43           4.9          3.1           1.5          0.1       0
44           5.1          3.8           1.9          0.4       0

In [ ]:
datatest = datatest.apply(pd.to_numeric)

In [ ]:
datatest_array = datatest.values

In [ ]:
xtest = datatest_array[:, :4]

In [ ]:
ytest = datatest_array[:,4]

In [ ]:
out = modelkita(xtest)

In [ ]:
out

<tf.Tensor: shape=(45, 3), dtype=float32, numpy=
array([[0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.17159013, 0.537633  , 0.29077685],
       [0.19202894, 0.50571007, 0.302261  ],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.26298445, 0.40680456, 0.33021098],
       [0.11344804, 0.6397871 , 0.24676484],
       [0.06857398, 0.73544276, 0.1959832 ],
       [0.17790367, 0.5275825 , 0.2945138 ],
       [0.12706012, 0.61409926, 0.25884065],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.06291208, 0.7491178 , 0.1879702 ],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.1826499 , 0.5201407 , 0.2972094 ],
       [0.11083099, 0.64487445, 0.24429457],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
       [0.3492088 , 0.3062413 , 0.34454986],
      

In [ ]:
prediction = tf.argmax(out, axis = 1)

In [ ]:
prediction

<tf.Tensor: shape=(45,), dtype=int64, numpy=
array([0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0])>

In [ ]:
ytest

array([0., 0., 1., 1., 0., 0., 0., 1., 2., 2., 1., 2., 0., 2., 0., 0., 1.,
       2., 0., 0., 0., 2., 2., 2., 1., 2., 0., 0., 2., 2., 0., 0., 0., 0.,
       2., 0., 2., 1., 2., 2., 1., 2., 1., 0., 0.])

In [ ]:
total_benar = tf.reduce_sum(tf.cast(tf.equal(prediction, ytest), tf.int32))

In [ ]:
accuration = total_benar/len(ytest) *100

In [ ]:
print("Accuracy os SGD with epochs 50, and 144 datatrain and 44 datatest is %.4f %%" % accuration)

Accuracy os SGD with epochs 50, and 144 datatrain and 44 datatest is 64.4444 %
